# Chapter 2: Statistics with R {#ch.statsR}

## Learning Objectives for Chapter

## R and RStudio {#sect.RnRStudio}

Use material from lab 1.
Point to R resoures and cheatsheets.

Give simple examples.

R will be a tool that we need to use, but it is not the goal of the course.

All code will be provided, with exception of very simple fill-in-the-blank exercises.

Should we use Rcmdr?

Explain structure of R Studio, topology of scripts, markdown files, directory, etc.

## Examples {#ch.statsR.ex01}

Provide and example of a simulation to determine the distribution of the sum of two independent uniform distributions. The definition of independence is found in Section \@ref(ch.Prob.indep) . Show analytic and simulation solutions. Show that analytic solution is general. Simulation may depend on the specific values selected to simulate.


this is 

## Exercises and Solutions

Use simulation and analytic/intuition to determine what happens when two uniform distributions are summed. Explore uniform distributions with different coefficients. Explain that the coefficients of the uniform distribution are the two ends of the "box."

Probability density function of the Uniform distribution U(a, b).

We write

$$x \sim U(a, b) \quad \text{where} \quad \quad a< b \quad (\#eq:unif.pdf)$$
to state that the continuous random variable $x$ has a uniform distribution between a and b. This means that the probability of obtaining a value of x in an interval $[x_1, x_2]$ within [a,b] is constant and equal to $(x_2-x_1)/(b-a)$ \@ref(fig:unif.dist.fig)

Note that the uniform distribution U(0, 1) is the distribution of the random numbers generated by the function RAND() in Excel. For more details on this distribution, see [Uniform Distribution] (https://en.wikipedia.org/wiki/Uniform_distribution_(continuous)#Minimum-variance_unbiased_estimator).

$$\begin{equation}
f(x) =
  \begin{cases}
    \frac{1}{b-a}       & \quad \text{if } a \leq x \leq b \\
    0                   & \quad \text{otherwise }
  \end{cases}
    (\#eq:unif.pdf)
\end{equation}$$


(ref:fig.unif.dist) Probability density function for the uniform distribution that has a support between any two values of the x-axis is the area under the line between those values.


```{r unif.dist.fig, fig.cap='(ref:fig.unif.dist)'}

# code for a unif dist with an interval and area selected
plot(cars)

```


## Exercises and Solutions


## Homework
