# Chapter 3:  Required Math Skills and Symbols {#ch.math}

## Learning Objectives for Chapter

1. Pair symbols with corresponding concepts or definitions.
1. Express sums using summation symbol and expand sums defined with the summation symbol.
1. Calculate sum of squared deviations for a set of numbers.
1. 

Jen's 
*I found this chapter hard, because I'm not sure of it's main objectives yet.  Broadly, is it just the concepts behind SS, and optimization?

1. Explain in your own words what the sum of squares of a set of numbers describes.  
2. Identify the symbols that correspond to standard deviation, variance, population mean, and sample average.  
3. List the different strategies we can use to find the optimal value for an unknown variable.


## Summation
## Deviations, sums of squares, sums of absolute deviations

The difference between an observation and the mean is called a "deviation" or "error."



## Geometry of sums of squares

Remember the Pythagorean theorem? In a right triangle the square of the hypothenuse equals the sum of teh squares of the sides. This can be extended to a polyhedron with right angles everywhere. The square of a diagonal in 3D is the sum of the three sides of the polyhedron. This square is also the sum of the square of the bottom hypothenuse and the vertical side suared. ** Add figure with labels** 
Imagine that we have a sample with 3 observations. Make a box where the lenght of each side is one of the observations and then consider the 3D diagonal. The sum of squares of the deviations is equal to the lenth of the diagonal.

The total sum of s

## Optimization

One way to "guess" or estimate the mean of a distribution that can be sampled directly is to take the average. The average minimizes the sum of the squared deviations of the obervations. Minimization of sums of squares is the most common method we will use to make estimates, but it is not the onlly method. Other method is to minimize the sum of the absolute deviations. The median of a set of observations is the value that minimizes the absolute deviations. "Absolute" means that all deviations are made positive.

Show an interactive graph where the values SS and SAD are shown as functions of the guessed mean. With and without outliers.

In many cases, the optimal value can be found analytically, which means that we can use an equation that yields the best estimate directly. This formula is obtained by taking the first derivative of the equation that calculates the SS as a function of the estimate, set it to zero and solve for the estimate. For more advanced statistical methods, there are no equations available, so numerical computations are used to approximated the optimal estimates.

Show pseudocode for an algorithm to find out what number I am thinking of or to numerically approximate a root of a polynomial

Say what a polynomial is.

## Complete list and definition of symbols used in the book



## Exercises and Solutions

## Homework

## Laboratory Exercises

### Plant Sciences

### Animal Sciences

