---
output: 
  html_document: 
    fig_caption: yes
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
---

# Experimental Design {#chEdesign}


See "TeachingExperimentalDesign2014.pdf"
"Chapter1.3-1.5.pdf"

## Learning Objectives for Chapter

1. List sources of possible error in an estimator for a variable of interest.
1. List ways that you could reduce or eliminate sampling bias
1. Identify the experimental unit of a given study design.
1. Explain the advantages of subsampling
1. Define experimental unit and identify them in given experiments.
1. Distinguish between **observational studies** and **manipulative** experiments.
1. Design experiments to get data to answer given research questions.
1. Pose research questions that can be addressed with statistical tests.
1. Distinguish between experimental design in its narrow sense and treatment structure.
1. Design factorial treatments using two factors.
1. Identify and use design feature to avoid confounding and to reduce error.

>"An experiment is characterized by the treatments and experimental units to be used, the way treatments are assigned to units, and the responses that are measured."
>
>Gary W. Oehlert, 2010 [@Oehlert2010]


## Manipulative and Observational Studies

There are two main types of studies involving collection, analysis and interpretation of data, manipulative and observational studies. The names given to these types of studies vary from author to author, but the fact that there are two main types doe not change. The difference is important because it determines what kind of conclusions can be derived from each type.

The main difference between manipulative and observational studies is that in manipulative studies the experimental units receive treatments in a way that involved a randomization at some point. In observational studies, observed units are selected at random but they do not receive any randomly assigned treatment or manipulation whose effects we are trying to study. For example, we may be interested in the effects of exercise on the time it takes to recover from a common cold. A random sample of 1000 people are selected and their level of exercise and duration of their illness -when they get a cold- are recorded. Suppose that strong negative relationship between amount of exercise and cold duration is found. This cannot be taken as evidence of a direct cause-and-effect relationship between exercise and cold duration. It may simply be a result of the fact that generally healtier people with stronger immune systems exercise more because they feel better in general, and they also have shorter colds due to the stornger immune system. Both the level of exercise and the duration of the cold have a common cause that creates the relationship between cold duration and exercise. There are other scenarios not involving a common cause that also generate associations without causation.

Conversely, if sets of 100 out of the 1000 people are randomly assigned to levels of exercise ranging from none to a lot, the randomization will break the potential associat`ion that is not causation. Each level of exercise will have people with all types of immune system and all types of any other variable that could possibly counfound the effects of exercise. If a relationship is found in this case, the argument for a causal relationship between exercise and duration of the cold is a lot stronger.

Manipulative experiments are the only ones that can address questions of causation. Causality cannot be established in observational studies because the treatments are not assigned independently of other characteristics of experimental units.

## Experimental Design and Treatment Structure

Experimental design in the narrow sense refers to the arrangement of experimental units and the manner in which treatments are assigned to experimental units. Experimental design determines the sources of errors and the apportioning of variance to typically uninteresting sources such as blocks.

Treatment design refers to the structure that may be present in the treatments, such as factorial, series of doses and controls. The treatment structure determines what comparisons are typically most useful.

Typically, experimental design and treatment structure fully determine the most complex model that may be necessary to analyze the data. The model determines the propoer analysis. However, in some cases the proper analysis also depends on the specific assumptions that can be made and on the questions to be
answered.

## Elements of Experimental Design

Oehlert [@Oehlert2010] provides the following definitions which are presented here with slight modification and additions:

*Treatments* are the different procedures we want to compare. These could be different kinds or amounts of fertilizer in agronomy, different long-distance rate structures in marketing, or different temperatures in a reactor vessel in chemical engineering.

*Experimental units* are the things to which we apply the treatments. These could be plots of land receiving fertilizer, groups of customers receiving different rate structures, or batches of feedstock processing at different temperatures.

*Responses* are outcomes that we observe after applying a treatment to an experimental unit. That is, the response is what we measure to judge what happened in the experiment; we often have more than one response. Responses for the above examples might be nitrogen content or biomass of corn plants, profit by customer group, or yield and quality of the product per ton of raw material.

*Randomization* is the use of a known, understood probabilistic mechanism for the assignment of treatments to units. Other aspects of an experiment can also be randomized: for example, the order in which units are evaluated for their responses.

*Experimental Error* is the random variation present in all experimental results. Different experimental units will give different responses to the same treatment, and it is often true that applying the same treatment over and over again to the same unit will result in different responses in different trials. Experimental error does not refer to conducting the wrong experiment or dropping test tubes.

*Measurement units* (or response units) are the actual objects on which the response is measured. These may differ from the experimental units. For example, consider the effect of different fertilizers on the nitrogen content of corn plants. Different field plots are the experimental units, but the measurement units might be a subset of the corn plants on the field plot, or a sample of leaves, stalks, and roots from the field plot. Measurement units are also known as *subsamples* and they are characterized by sharing a common experimentla unit error component.

*Blinding* occurs when the evaluators of a response do not know which treatment was given to which unit. Blinding helps prevent bias in the evaluation, even unconscious bias from well-intentioned evaluators. Double blinding occurs when both the evaluators of the response and the (human subject) experimental units do not know the assignment of treatments to units. Blinding the subjects can also prevent bias, because subject responses can change when subjects have expectations for certain treatments.

*Controlled experiment* has several different uses in design. An experiment is controlled because we as experimenters assign treatments to experimental units. Otherwise, we would have an observational study. Control also refer to the selection of experimental material that is homogeneous to reduce unexplained variation or error.

*Control Treatments*. A control treatment is a “standard” treatment that is used as a baseline or basis of comparison for the other treatments. This control treatment might be the treatment in common use, or it might be a null treatment (no treatment at all). For example, a study of new pain killing drugs could use a standard pain killer as a control treatment, or a study on the efficacy of fertilizer could give some fields no fertilizer at all. This would control for average soil fertility or weather conditions.

*Placebo* is a null treatment that is used when the act of applying a treatment— any treatment—has an effect. Placebos are often used with human subjects, because people often respond to any treatment: for example, reduction in headache pain when given a sugar pill. Blinding is important when placebos are used with human subjects. Placebos are also useful for nonhuman subjects. The apparatus for spraying a field with a pesticide may compact the soil. Thus we drive the apparatus over the field, without actually spraying, as a placebo treatment. This use of the word "placebo" is unusual in agriculture. Usually we call these "controls" and have different types of control treatments. For the example of spraying, we could have a "placebo" control with the driving of the equipment, and a "naive" control without it. The important point is to correclty interpret the meaning of the differences between any two treatments. The difference between spray and placebo is the effect of the spray compound

*Factors* combine to form treatments. For example, the baking treatment for a cake involves a given time at a given temperature. The treatment is the combination of time and temperature, but we can vary the time and temperature separately. Thus we speak of a time factor and a temperature factor. Individual settings for each factor are called *levels* of the factor.

*Confounding* occurs when the effect of one factor or treatment cannot be distinguished from that of another factor or treatment. The two factors or treatments are said to be confounded. Except in very special circumstances, confounding should be avoided. Consider planting corn variety A in Minnesota and corn variety B in Iowa. In this experiment, we cannot distinguish location effects from variety effects—the variety factor and the location factor are confounded.


